defaults:
  - shared/training
  - shared/tuning 
  - model_type: schnet # is in reality a model_selector (mlp, gcn, schnet)
  - preprocessor: preprocessor
  - training: schnet
  - tuning: schnet
  - override hydra/launcher: joblib
  - _self_


random_state: 42
exp_name: qm9
run_tuning_name: tuning
run_training_name: training
hydra:
  launcher:
    n_jobs: 1


